# Default initial positions for irb6640_205's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  screwdriver-screwdriver_tcp: 0
  screwdriver-screwdriver_tcp_dummy: 0