# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - irb_arm_group_controller
    - irb_eff_group_controller
    # - fake_irb_eff_group_controller
    - irb_arm_w_screw_group_controller

  # irb_arm_group_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6
  # fake_irb_eff_group_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - screwdriver-screwdriver_tcp_dummy
  irb_arm_w_screw_group_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - screwdriver-screwdriver_tcp_dummy
    action_ns: follow_joint_trajectory
    default: true